package(default_visibility = ["//visibility:public"])

alias(
  name = "api",
  actual = "//domjudge/api:api",
)

alias(
  name = "proto",
  actual = "//domjudge/proto:proto",
)

alias(
  name = "scoreboard",
  actual = "//domjudge/scoreboard:scoreboard",
)
