package(default_visibility = ["//visibility:public"])

java_library(
  name = "contest",
  srcs = glob([
    "src/java/**",
  ]),
  deps = [
    "//clics/api",
    "//clics/proto",
    "//domjudge/api",
    "//domjudge/proto",
    "//interop",
    "@auto_value//:processor",
  ]
)
