package(default_visibility = ["//visibility:public"])

java_library(
  name = "utils",
  srcs = glob([
    "utils/src/java/**/*.java"
  ]),
  deps = [
    "//domjudge:api",
    "//domjudge:proto",
  ],
)

