package(default_visibility = ["//visibility:public"])

java_library(
  name = "utils",
  srcs = glob([
    "src/java/**"
  ]),
  deps = [
    "//third_party/gson:prototype_adapter",
    "//external:gson",
    "//external:guava",
    "@okhttp//jar",
    "@okio//jar",
  ],
)
