package(default_visibility = ["//visibility:public"])

java_library(
  name = "interop",
  srcs = glob([
    "src/java/**"
  ]),
  deps = [
    "//api/clics/proto:java",
    "//api/domjudge/proto:java",
    "@com_google_protobuf//:protobuf_java",
  ],
)
