package(default_visibility = ["//visibility:public"])

java_library(
  name = "interop",
  srcs = glob([
    "src/java/**"
  ]),
  deps = [
    "//clics/proto:java",
    "//domjudge/proto:java",
    "@com_google_protobuf//:protobuf_java",
  ],
)
